# steps:
#    - name: "gcr.io/cloud-builders/docker"
#      args: ["build", "-t", "gcr.io/$PROJECT_ID/nodeservice:$COMMIT_SHA", "."]
#    - name: "gcr.io/cloud-builders/docker"
#      args: ["push", "gcr.io/$PROJECT_ID/nodeservice:$COMMIT_SHA"]
#    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#      entrypoint: gcloud
#      args:
#         - "run"
#         - "deploy"
#         - "nodeservice"
#         - "--image"
#         - "gcr.io/$PROJECT_ID/nodeservice:$COMMIT_SHA"
#         - "--region"
#         - "australia-southeast1"
# images:
#    - "gcr.io/$PROJECT_ID/nodeservice:$COMMIT_SHA"

steps:
   # Build the container image
   - name: "gcr.io/cloud-builders/docker"
     args: ["build", "-t", "gcr.io/static-website-project-400707/nodejsimage", "."]
   # Push the container image to Container Registry
   - name: "gcr.io/cloud-builders/docker"
     args: ["push", "gcr.io/static-website-project-400707/nodejsimage"]
   # Deploy container image to Cloud Run
   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
     entrypoint: gcloud
     args:
        [
           "run",
           "deploy",
           "nodeservice",
           "--image",
           "gcr.io/static-website-project-400707/nodejsimage",
           "--region",
           "australia-southeast1",
        ]
images:
   - gcr.io/static-website-project-400707/nodejsimage
